### ISSUE TITLE
Support source view when exception is caused from a spring proxy of a user class

### ISSUE THREAD

**Issue by destan** [kodgemisi/better-error-pages-spring-boot-starter#6]
Implementation notes:

* There is no line number info in such trace
* We may find the relevant line number via the method name but it doesn't seem very reliable
* We can just load the whole java source file
* example regex `at (com\.example\.springcourse[a-z0-9\\.]*\.([A-Z]\w*))\$\$.*\.(\w+\(.*\))`

![image](https://user-images.githubusercontent.com/442813/39580212-4f41118e-4ef1-11e8-8963-68a052c2b1cc.png)

example trace:

```
org.springframework.security.access.AccessDeniedException: Access is denied at org.springframework.security.access.vote.AffirmativeBased.decide(AffirmativeBased.java:84) at org.springframework.security.access.intercept.AbstractSecurityInterceptor.beforeInvocation(AbstractSecurityInterceptor.java:233) at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:65) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689) at com.example.springcourse.users.UsersController$$EnhancerBySpringCGLIB$$133b6581.list() at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209) at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136) at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102) at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:877) at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:783) at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991) at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925) at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:974) at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:866) at javax.servlet.http.HttpServlet.service(HttpServlet.java:635) at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:851) at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
```

**Comment by destan** [comment]
`at ((com.example.springcourse[a-z0-9\.]*)\.([A-Z]\w*)).*\((?:(.+):(\d+)){0,1}\)`

need to make the word+number selection between parenthesis optional `\((.+):(\d+)\)` -> `\((?:(.+):(\d+)){0,1}\)`

note that we need to use a non-capturing group to don't break compatibility.
